# Generated by Django 5.2.10 on 2026-07-05 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('error_rate', 'Error rate'), ('latency', 'Latency')], max_length=20)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('observed_value', models.FloatField()),
                ('baseline_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed')], db_index=True, default='active', max_length=20)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dedup_key', models.CharField(max_length=560)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='projects.app')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='projects.project')),
            ],
            options={
                'db_table': 'alert_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status', '-created_at'], name='alert_event_project_c1ce3e_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'dedup_key'), name='unique_alert_dedup_per_project')],
            },
        ),
    ]
