# Generated by Django 5.2.10 on 2026-07-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alertevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHeartbeat',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField()),
                ('last_scanned', models.IntegerField(default=0)),
                ('last_created', models.IntegerField(default=0)),
                ('last_duration_ms', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'job_heartbeats',
            },
        ),
    ]
