# Generated by Django 5.2.10 on 2026-07-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_jobheartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
