# Generated by Django 5.2.10 on 2026-07-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alertevent_viewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='anomaly_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
